# Generated by Django 6.0.7 on 2026-08-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Película'), ('series', 'Serie')], default='movie', max_length=10),
        ),
    ]
